# Generated by Django 2.0.4 on 2018-04-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20180420_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
    ]
