# Generated by Django 2.0.4 on 2018-04-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20180420_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='red_feitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('P', 'Esta informação é particular')], default='P', max_length=1, null=True),
        ),
    ]
