# Generated by Django 2.0.4 on 2018-04-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_auto_20180427_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('P', 'Esta informação é particular')], default='P', max_length=1, null=True, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ingresso_ensino_medio',
            field=models.DateField(default=None, null=True, verbose_name='ingresso no ensino médio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(default=None, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primeiro_nome',
            field=models.CharField(max_length=12, verbose_name='primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='segundo_nome',
            field=models.CharField(max_length=30, verbose_name='segundo Nome'),
        ),
    ]
