# Generated by Django 2.0.4 on 2018-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0014_auto_20180502_1259'),
        ('Usuarios', '0007_auto_20180427_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='redacoes',
            field=models.ManyToManyField(to='Redacao.Redacao'),
        ),
    ]
