# Generated by Django 2.0.4 on 2018-05-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_user_redacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ingresso_ensino_medio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='red_feitas',
        ),
    ]
