# Generated by Django 2.0.4 on 2018-05-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_auto_20180502_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primeiro_nome',
            field=models.CharField(max_length=20, verbose_name='primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='segundo_nome',
            field=models.CharField(max_length=60, verbose_name='segundo Nome'),
        ),
    ]
