# Generated by Django 2.0.4 on 2018-04-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redacao', models.ImageField(upload_to='Redacoes')),
                ('correcao', models.ImageField(null=True, upload_to='Correcoes')),
                ('aluno', models.EmailField(max_length=255)),
                ('professor', models.EmailField(max_length=255)),
                ('pago', models.BooleanField(default=False)),
                ('dataPagamento', models.DateField(default=None, null=True)),
                ('nota_competencia_1', models.IntegerField(default=0, null=True)),
                ('nota_competencia_2', models.IntegerField(default=0, null=True)),
                ('nota_competencia_3', models.IntegerField(default=0, null=True)),
                ('nota_competencia_4', models.IntegerField(default=0, null=True)),
                ('nota_competencia_5', models.IntegerField(default=0, null=True)),
                ('nota', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
