# Generated by Django 2.0.4 on 2018-04-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redacao',
            name='pago',
        ),
    ]
