# Generated by Django 2.0.4 on 2018-04-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0002_remove_redacao_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='correcao',
            field=models.ImageField(null=True, upload_to='Correcoes/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='redacao',
            field=models.ImageField(upload_to='Redacoes/%Y/%m/%d'),
        ),
    ]
