# Generated by Django 2.0.4 on 2018-04-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0003_auto_20180423_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='correcao',
            field=models.ImageField(null=True, upload_to='Correcoes'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='redacao',
            field=models.ImageField(default='Redacoes/1.png', upload_to='Redacoes'),
        ),
    ]
