# Generated by Django 2.0.4 on 2018-04-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0004_auto_20180423_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='redacao',
            field=models.ImageField(default='Redacoes/1.jpg', upload_to='Redacoes'),
        ),
    ]
