# Generated by Django 2.0.4 on 2018-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0005_auto_20180423_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redacao',
            name='redacao',
        ),
        migrations.AddField(
            model_name='redacao',
            name='texto',
            field=models.ImageField(default='Redacoes/1.jpg', null=True, upload_to='Redacoes'),
        ),
    ]
