# Generated by Django 2.0.4 on 2018-04-23 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0007_auto_20180423_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='corrigida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='dataPagamento',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
