# Generated by Django 2.0.4 on 2018-04-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0008_auto_20180423_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redacao',
            old_name='dataPagamento',
            new_name='data_pagamento',
        ),
    ]
