# Generated by Django 2.0.4 on 2018-04-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0009_auto_20180425_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redacao',
            old_name='data_pagamento',
            new_name='data_pedido',
        ),
    ]
