# Generated by Django 2.0.4 on 2018-04-25 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0010_auto_20180425_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
