# Generated by Django 2.0.4 on 2018-04-27 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0011_auto_20180425_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='proposta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redacao',
            name='correcao',
            field=models.ImageField(null=True, upload_to='Correcoes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redacao',
            name='redacao',
            field=models.ImageField(null=True, upload_to='Redacoes/%Y/%m/%d/'),
        ),
    ]
