# Generated by Django 2.0.4 on 2018-05-02 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Redacao', '0013_auto_20180427_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redacao',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='redacao',
            name='professor',
        ),
        migrations.AddField(
            model_name='redacao',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
