# Generated by Django 2.0.4 on 2018-05-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0015_remove_redacao_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=110)),
                ('numero', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='Propostas/%Y/%m/')),
            ],
        ),
        migrations.AlterField(
            model_name='redacao',
            name='proposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Redacao.Proposta'),
        ),
    ]
