# Generated by Django 2.0.4 on 2018-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0016_auto_20180503_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='em_uso',
            field=models.BooleanField(default=False),
        ),
    ]
