# Generated by Django 2.0.4 on 2018-05-08 12:36

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0017_proposta_em_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='imagem',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket='other-bucket'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='correcao',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='other-bucket'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='redacao',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='other-bucket'), upload_to=''),
        ),
    ]
