# Generated by Django 2.0.4 on 2018-05-09 11:30

import Redacao.storage_backend
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('Redacao', '0018_auto_20180508_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='imagem',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='propostas'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='correcao',
            field=models.ImageField(null=True, storage=Redacao.storage_backend.RedacoesStorage(), upload_to='correcoes'),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='redacao',
            field=models.ImageField(null=True, storage=Redacao.storage_backend.RedacoesStorage(), upload_to='redacoes'),
        ),
    ]
